# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c00ba4e6e40394d182ee33a59b88e8a90a2ce11f14bcf41bb64258f2d84ad3849a75da0fe9aac888079fe0aa91956892b904178759edee5b3df1a2323ab2a85

test:
  secret_key_base: e45b9fb9b7a9d4d92010b6649355a36ea25f2764074ab5d92df1665dc144606fa9df02e4b0d2a63ec1f7f97cac57c7465be734d45a5c4d008a8a0424b6c127c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
